# Generated by Django 3.1 on 2020-08-29 02:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smoothie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmoothieIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('smoothies', models.ManyToManyField(to='api.Smoothie')),
            ],
        ),
    ]
