# Generated by Django 3.1 on 2020-09-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smoothie',
            name='user_id',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smoothieingredient',
            name='user_id',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smoothie',
            name='name',
            field=models.TextField(default='00000000-0000-0000-0000-000000000000', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
